branch-defaults:
  default:
    environment: django-venv
  master:
    environment: django-venv
global:
  application_name: django-tut
  branch: null
  default_ec2_keyname: null
  default_platform: python
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
